### ISSUE TITLE
audit feature

### ISSUE THREAD

**Issue by Wangmin362** [tsl0922/ttyd#1085] opened 2023-03-08 09:42 UTC
**Is your feature request related to a problem? Please describe.**
no related problem

**Describe the solution you'd like**
i want to record any command from ttyd, how to relolve?

**Describe alternatives you've considered**

**Additional context**

**Comment by tsl0922** [comment] 2023-03-08 12:59
duplicate of #251

**Closed by tsl0922** 2023-03-08 12:59 UTC
Labels: enhancement
