### ISSUE TITLE
Porting to OpenBSD : length mismatch and invalid return

### ISSUE THREAD

**Issue by dohnuts** [tsl0922/ttyd#43] opened 2017-03-03 18:25 UTC
Hello,

After fixing compilation ( just a few defines for STAILQ and c99 )
i am trying to run the daemon.

It stays in this state and does not provide content
```
[2017/03/03 12:52:26:0036] NOTICE: wsi 0xc3e80cef600: TIMEDOUT WAITING on 3 (did hdr 0, ah 0xc3ee9c7d000, wl 0, pfd events 0)
[2017/03/03 12:52:26:0047] NOTICE: lws_header_table_detach: wsi 0xc3e80cef600: ah held 6s, ah.rxpos 0, ah.rxlen 0, mode/state 0 4,wsi->more_rx_waiting 0
```

i ran it like this : 
`ttyd -O --debug 7 --index /usr/ports/pobj/ttyd-1.3.0/ttyd-1.3.0/html/index.html /bin/ksh`

When the daemon serve small file it s okay, but it looks like the c code forgot to write when 
the socket is ready.

curl http://127.0.0.1/ show the html package file is cut :

`break;case"m":p="0m";break;default:this._terminal.error("Unknown DCS Pt: %s.",p),p=""}this._terminal.send(s.C0.ESC+"P"+ +f+"$r"+p+s.C0.ESC+"\\");break;case"+p":break;case"+q":p=this._terminal.currentParam,f=!1,this._terminal.send(s.C0.ESC+"P"+ +f+"+r"+p+s.C0.ESC+"\\");break;default:this._terminal.error("Unknown DCS prefix: %s.",this._terminal.prefix)}this._terminal.currentParam=0,`

By using nginx/1.10.1 as  a proxy see https://www.nginx.com/blog/websocket-nginx/

i can load the all index.html but other error occurs :
 * `WebSocket connection to 'ws://my.com/index.htmlws' failed: Error during WebSocket handshake: Unexpected response code: 502`

Because the full referrer of my request is used ( i called with index.html )

By playing arounf with nginx i got something working but the issues should be fixed.

**Comment by tsl0922** [comment] 2017-03-04 05:29
ttyd is not tested on OpenBSD yet, PRs are welcomed.

**Comment by tsl0922** [comment] 2017-03-09 14:25
Merged #44.

I don't have OpenBSD environment right now, will check the issue you reported later.

**Comment by tsl0922** [comment] 2017-03-22 02:06
Reproduced this issue on OpenBSD 6.0 last night.

However, I can't reproduce it on macOs 10.12.3, this may be an issue of the `lws_serve_http_file`  method which comes from [libwebsockets](https://github.com/warmcat/libwebsockets).

**Comment by dohnuts** [comment] 2017-04-24 21:29
I tested the sofware with the proposed file change following
https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-http.c#L413

**Closed** 2017-04-25 12:34 UTC
Labels: bug

**Comment by tsl0922** [comment] 2017-04-25 12:38
Thanks @dohnuts ! Works great 👍 

I've applied your patch with some modifications.
