### ISSUE TITLE
100% cpu usage with Midnight Commander

### ISSUE THREAD

**Issue by zella** [tsl0922/ttyd#157] opened 2019-02-07 01:19 UTC
I run `docker run -it --rm -p 7681:7681 tsl0922/ttyd` 

then install and run Midnight commander:  
`apt-get update && apt-get install mc && mc` 

Cpu usage become 100%  until I exit mc.  

Ubuntu 18.04, cpu - xeon 8 threads

**Comment by tsl0922** [comment] 2019-03-03 03:08
Duplicate of #136,  I'm closing this one.

**Comment by tsl0922** [comment] 2019-03-03 03:12
Sorry, it seems like you are reporting a backend issue?

**Comment by tsl0922** [comment] 2019-03-03 03:15
Can not reproduce on my machine (running the command you given on docker on mac).

**Closed** 2019-04-14 10:59 UTC

**Comment by patrickelectric** [comment] 2021-12-03 18:33
I got the same problem on docker running on a raspberry, it was necessary to use --privileged option.
