### ISSUE TITLE
low throughput

### ISSUE THREAD

**Issue by jerch** [tsl0922/ttyd#247] opened 2019-11-24 13:39 UTC
Compared with the demo in xterm.js ttyd is ~6 times slower for heavy output (68s vs. 12s, tested with `ls -lR /usr` at 80x25 terminal). It seems you have some throttling or flow control in the server part (did not look at the code though), `yes` is pretty snappy with Ctrl-C. Also zmodem seems to penalize this further but on a much lower level (adds ~3s in the test above).

We have recently extended the write call with an optional callback, that gets triggered when the parsing of the chunk was finished. With this you can implement a real flow control that better reflects how far xterm.js has fallen behind (see https://xtermjs.org/docs/guides/flowcontrol/ for some ideas).

**Comment by tsl0922** [comment] 2019-11-24 16:27
It's a known issue to me on ttyd's server side (will select/poll model), decreasing the [sleep time](https://github.com/tsl0922/ttyd/blob/master/src/server.c#L506) in the main loop helps with throughput, but the CPU usage will go high too.

**Comment by jerch** [comment] 2019-11-24 16:42
Have you tried with a tiny timeout in select here: https://github.com/tsl0922/ttyd/blob/d88053b884f9b0f7be0cc84580624655f7d28eb5/src/protocol.c#L219

It would avoid the busy waiting and you can prolly remove the sleep. If you have other busy pollers in the loop (did not check) it might be worth to refactor all pollers to be waited for in one step with poll (has slight advantage over select). If you target linux only epoll would be the best choice perfwise.

**Comment by tsl0922** [comment] 2019-11-26 14:04
Thanks, adding timeout to the select call improves throughput a lot(6d69f0a55d4e7e647d949f8608dc8501ebfa9e52), I will refact the code with the poll approach in the feature.

It seems possible to get all the poll called in one step with libwebsockets's [External Polling Loop support](https://libwebsockets.org/lws-api-doc-master/html/md_READMEs_README_8coding.html#extpoll).

**Comment by jerch** [comment] 2019-11-26 14:28
@tsl0922 Yeah as expected, it is basically "sleeping" now at the `select` with the difference to wake as soon as data is available. Thus its a good idea to put all polls into one step (unless you want to go the threading route).

But keep in mind - now it is very likely that a signal will disrupt `select` (or `poll` later on). You will need additional error handling for this, either test and handle `EINTR` explicitly or go the BSD route with `TEMP_FAILURE_RETRY` (the latter will make it BSD compatible, thus less ugly `#if defined(__linux__)` switches). Also you should apply the same to any other syscall used like `read`, `write` and such. See a list of affected syscalls in the [signal manpage](http://man7.org/linux/man-pages/man7/signal.7.html).

**Comment by tsl0922** [comment] 2019-11-27 16:05
I'm going to use libwebsockets with [libuv](https://libuv.org/) as event backend, which may solves the issue you mentioned.

Here is a working preview version: https://github.com/tsl0922/ttyd/commits/libuv.

**Comment by jerch** [comment] 2019-11-27 18:33
@tsl0922 Prolly much easier to accomplish with libuv yepp. 2 things I noticed with it:

- after start without any client ttyd takes 100% CPU (some hidden busy wait for client connection?)
- running `yes` + pressing Ctrl-C takes now very low to finish. This is due to the sheer amount of data `yes` produces, it fills up websocket buffers and evtl. leads to a crash. Thats the point where flow control should slow down the application behind the pty. You can use the callback on `Terminal.write` to create some backpressure measuring.

Throughput is now much better (12s for `ls -lR /usr`). There is one more bit to optimize websocket usage - if the application produces very short messages in short time its better to prebuffer them into one bigger chunk before sending over websocket. Many short websocket message create high callback pressure in the browser - if you do a perf measuring in chrome-devtools youll see that the browser is half of the time busy with websocket callbacks (thats the greyish part in the runtime pie chart). If you collect the messages on server side by some tiny time limit (5 - 15ms) into one bigger chunk, that runtime will drop by 70%.

**Comment by tsl0922** [comment] 2019-11-28 03:17
@jerch What's your OS and libwebsockets version? Although cant reproduce the 100% on my machine (macOS 10.15, libwebsockets 3.2.0), I should give `lws_service` a tiny timeout too, it uses poll internally.

**Comment by jerch** [comment] 2019-11-28 10:48
@tsl0922 ubuntu 18.04 LTS with the default distro package libwebsockets8 v2.0.3.

**Comment by tsl0922** [comment] 2019-11-30 02:08
@jerch still can't reproduce the 100% CPU issue on the latest master, can you try again?

libwebsockets changes it's api and internals quickly, I'm a little tired of following up, maybe I'll drop support for the old versions later (the 1.x and 2.x version).

**Comment by jerch** [comment] 2019-12-02 10:57
@tsl0922 Ah maybe I was on some intermediate code, after a fresh pull & compile the 100% issue is gone :+1:

**Comment by scopatz** [comment] 2019-12-03 22:00
FWIW, I am seeing this too on an Ubuntu 19.04 box

**Comment by jerch** [comment] 2019-12-04 10:10
Hmm I double checked it, for me the 100% issue is gone now, weird.

**Comment by tsl0922** [comment] 2019-12-04 10:34
@scopatz what's your  libwebsockets version?

**Comment by jerch** [comment] 2019-12-04 11:13
@tsl0922 Not sure how big libwebsockets is - maybe its easier to do deliver a certain version with ttyd and link it statically? It will slightly increase the maintenance burden of that lib, but since they are not very stable API-wise (as you indicated), you have that burden anyway.

**Comment by tsl0922** [comment] 2019-12-04 11:20
Statically linked version is already provided on the release page, ttyd was
mainly for embed devices like router at first, static version’s binary size
is not suitable for routers with small flash.

jerch <notifications@github.com>于2019年12月4日 周三19:13写道：

**Comment by scopatz** [comment] 2019-12-04 14:09
@tsl0922 - I am using libwebsockets v3.2.0 with libuv

**Comment by tsl0922** [comment] 2019-12-11 13:16
I'm closing this issue, it should be fixed on the master branch now.

**Closed by tsl0922** 2019-12-11 13:16 UTC
