### ISSUE TITLE
Compile error on ubuntu 14.04

### ISSUE THREAD

**Issue by goxofy** [tsl0922/ttyd#19] opened 2016-10-25 14:50 UTC
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.1f") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'libwebsockets>=1.7.0'
--   package 'libwebsockets>=1.7.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:23 (pkg_check_modules)

-- Found LIBWEBSOCKETS: /usr/lib/i386-linux-gnu/libwebsockets.so  
-- Looking for lws_config.h
-- Looking for lws_config.h - not found
-- checking for module 'json-c'
--   found json-c, version 0.11.99
-- Found JSON-C: /usr/lib/i386-linux-gnu/libjson-c.so  
-- Configuring incomplete, errors occurred!
See also "/home/tink/ttyd/build/CMakeFiles/CMakeOutput.log".
See also "/home/tink/ttyd/build/CMakeFiles/CMakeError.log".

**Comment by tsl0922** [comment] 2016-10-26 00:44
Duplicate of #6.

ubuntu versions old than 16.04 have outdated libwebsockets-dev package, you need to compile it yourself.

**Closed by tsl0922** 2016-10-26 00:44 UTC

**Comment by goxofy** [comment] 2016-10-26 08:38
ok
thanks
