### ISSUE TITLE
Please consider updating the README and a new 2022 release

### ISSUE THREAD

**Issue by m040601** [tsl0922/ttyd#890] opened 2022-03-01 05:29 UTC
UPDATE: Archlinux problem seems to be solved now.

Hi, thanks for your work in this tool. Very usefull and interesting also on OpenWrt and the Raspberry Pi.

We're trying to figure out why is it not installing on Archlinux as of March 2022. Both  x86_64 and ARM versions. Both the stable/released version and the git version.

https://aur.archlinux.org/packages/ttyd

Since the last release in January 2021 there have been a lot of changes in the code.

Would you consider releasing a new version now in 2022 ?

Since the last release in January 2021, the README file itself, hasnt changed. Were there any changes in the requirements that might be needed to document ?

```
Features:
....
Cross platform: macOS, Linux, FreeBSD/OpenBSD, OpenWrt, Windows
```

I see that you are also the Openwrt package maintainer.
It is indeed very a very interesting thing to use there.

I'm super curious to know about real world uses and feedback about running and using this on Openwrt. If you could add some to the README also 

Thanks in advance

**Comment by aigarius** [comment] 2022-03-28 09:21
Also the Dockerfile does not actually build the tool from the repo, which is highly annoying

**Comment by tsl0922** [comment] 2022-08-05 04:03
Duplicate of #784 

> I'm super curious to know about real world uses and feedback about running and using this on Openwrt. If you could add some to the README also
Read the [Wiki](https://github.com/tsl0922/ttyd/wiki)

**Closed by tsl0922** 2022-08-05 04:03 UTC
Labels: question
