### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by liudf0716** [tsl0922/ttyd#60] opened 2017-07-13 09:49 UTC
![tyyd_segmentfault](https://user-images.githubusercontent.com/1182593/28160657-89f823d4-67f3-11e7-98a7-a99b127e0c5d.png)

**Comment by tsl0922** [comment] 2017-07-24 08:24
What's your system? Is this reproducible?

**Comment by liudf0716** [comment] 2017-07-25 02:34
yes, it can easily reproduce. on ubuntu system.

**Comment by tsl0922** [comment] 2017-07-25 02:36
How? Can you give me some step.

**Comment by liudf0716** [comment] 2017-07-25 02:51
when I use [xfrps](https://github.com/KunTengRom/xfrps) as reverse proxy for ttyd, firstly as http service type and visit it remotely, failed, then as tcp service type and visit it, sementfault.

**Comment by frenck** [comment] 2017-09-04 19:18
I might have some reproductions in hassio-addons/addon-terminal#4 as well.

**Comment by tsl0922** [comment] 2017-09-06 12:21
@liudf0716 I've tested xfrps on osx, but can't reproduce it. I'll test it on ubuntu when I get a 
 proper environment. It will help me If you can give some more information like: ubuntu version, ttyd version and libwebsockets version it compiled with (full ttyd log is better).

**Comment by frenck** [comment] 2017-09-12 09:21
@tsl0922 I've got a log that might help?

```txt
[2017/08/25 15:37:02:1351] NOTICE: ttyd 1.3.2 (libwebsockets 2.2.0)
[2017/08/25 15:37:02:1352] NOTICE: tty configuration:
[2017/08/25 15:37:02:1352] NOTICE: start command: tmux new -A -s ttyd zsh
[2017/08/25 15:37:02:1352] NOTICE: reconnect timeout: 30s
[2017/08/25 15:37:02:1352] NOTICE: close signal: SIGHUP (1)
[2017/08/25 15:37:02:1352] NOTICE: Initial logging level 7
[2017/08/25 15:37:02:1353] NOTICE: Libwebsockets version: 2.2.0 buildozer@build-3-6-armhf-v3.5.0-4177-gcff862c329
[2017/08/25 15:37:02:1353] NOTICE: IPV6 not compiled in
[2017/08/25 15:37:02:1353] NOTICE: libev support not compiled in
[2017/08/25 15:37:02:1353] NOTICE: libuv support not compiled in
[2017/08/25 15:37:02:1354] NOTICE: Threads: 1 each 1048576 fds
[2017/08/25 15:37:02:1578] NOTICE: mem: platform fd map: 4194304 bytes
[2017/08/25 15:37:02:1581] NOTICE: Compiled with OpenSSL support
[2017/08/25 15:37:02:1581] NOTICE: SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2017/08/25 15:37:02:1582] NOTICE: Creating Vhost 'default' port 7681, 2 protocols, IPv6 off
[2017/08/25 15:37:02:1583] NOTICE: Listening on port 7681
[2017/08/25 15:37:02:1583] NOTICE: mem: per-conn: 448 bytes + protocol rx buf
[2017/08/25 15:37:02:1583] NOTICE: canonical_hostname = a0d7b954-terminal
[2017/08/25 15:37:02:1584] NOTICE: listening on port 7681
[2017/08/25 15:37:39:7955] NOTICE: HTTP / - 172.30.32.1 (homeassistant)
[2017/08/25 15:37:39:8332] NOTICE: HTTP /auth_token.js - 172.30.32.1 (homeassistant)
[2017/08/25 15:37:39:8438] NOTICE: WS /ws - 172.30.32.1 (homeassistant), clients: 1
[2017/08/25 15:37:39:8488] NOTICE: started process, pid: 39
/run.sh: line 375: 37 Segmentation fault (core dumped) ttyd -d 7 --reconnect 30 --port 7681 tmux new -A -s ttyd zsh
```

This is in a Docker container based upon Alpine

**Comment by BlackDex** [comment] 2017-10-16 10:01
I have had the same problem when using SSL.
Only if i change the debug level it seems to work.
For me -d2 works, also -d10 seemed to work, but -d2 gives me less info which i do not need anyway for now.

**Comment by stncrn** [comment] 2018-01-06 17:38
Same issue on Ubuntu 16.04x64: 

Segmentation fault in SSL server mode, with odd debug levels. 
No issues in plain http, nor in mutual SSL, nor in SSL server with even debug levels.

**Works** : 
ttyd -p 80 -c admin:admin -u 1001 bash
ttyd -d 0 -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash
ttyd -d 2 -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash
ttyd -d 4 -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash
ttyd -d 6 -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash
ttyd -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash -A /path/ca.cer

**Segmentation fault :** 
ttyd -d 1 -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash
ttyd -d 3 -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash
ttyd -d 5 -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash
ttyd -d 7 -p 443 -c admin:admin -u 1001 -S -C /path/cert.cer -K /path/key.key bash

**Comment by tsl0922** [comment] 2018-01-07 02:14
I've compiled a static version (linux x64) of the master branch, please check if it works.

[ttyd-master.zip](https://github.com/tsl0922/ttyd/files/1609428/ttyd-master.zip)

**Comment by tsl0922** [comment] 2018-01-13 10:02
Should be fixed on master, please open new issue if it occurs again.

**Closed by tsl0922** 2018-01-13 10:02 UTC
Labels: bug
