### ISSUE TITLE
ttyd crashes or becomes unresponsive

### ISSUE THREAD

**Issue by realies** [tsl0922/ttyd#83] opened 2017-12-31 01:43 UTC
Closing the web terminal window before it has fully loaded (i.e. during the completely black screen), `ttyd` would sometimes lock and utilise its thread to 100% or exit with a segmentation fault.

Used with a Nginx's `proxy_pass` to the unix socket and initialised with `exec ttyd -d 0 -i /var/run/ttyd.sock bash -l &>/dev/null &` on kernel 4.14.9-unRAID.

**Comment by tsl0922** [comment] 2018-01-07 08:06
Can you test if the latest master version crashes?

**Comment by eschultz** [comment] 2018-01-07 14:35
latest master version works great now in Edge and IE11.  Thanks!

**Comment by tsl0922** [comment] 2018-01-08 06:14
@realies try adding `-s SIGKILL` to ttyd's command line argument, this forces kill (`kill -9`) client session when websocket connection closes.

**Comment by realies** [comment] 2018-01-08 15:38
@tsl0922, latest master still has the issue. Adding `-s SIGKILL` does not change the behaviour. Running `ttyd` as `ttyd -p 8080 bash -x -s SIGKILL`. Log before it hangs to 100% thread usage:

```
[1515425686:9908] ERR: lws_callback_on_writable: failed to find socket -1
[1515425687:0009] ERR: lws_callback_on_writable: failed to find socket -1
[1515425687:0111] ERR: lws_callback_on_writable: failed to find socket -1
[1515425687:0623] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 2
```

**Comment by tsl0922** [comment] 2018-01-08 15:40
@realies `-s SIGKILL` is ttyd's argument, you should run `ttyd -s SIGKILL -p 8080 bash -x`

**Comment by realies** [comment] 2018-01-08 15:43
Please ignore the typo, running as `ttyd -s SIGKILL -p 8080 bash -x`.

When it crashes, the output is:
```
[1515426087:3746] ERR: lws_callback_on_writable: failed to find socket -1
[1515426087:3747] ERR: lws_callback_on_writable: failed to find socket -1
[1515426087:3747] ERR: lws_callback_on_writable: failed to find socket -1
[1515426087:4189] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
Segmentation fault (core dumped)
```

**Comment by tsl0922** [comment] 2018-01-08 16:37
Thanks for the detailed info. I can reproduce the client count issue, but cant not reproduce the 100% CPU usage (proxying ttyd's unix socket with nginx on macOS and tested with Chrome/Firefox), will try to reproduce it on linux later.

I guess some browsers may not close websocket connection when leaving the page (to be confirmed), ttyd replies on this to cleanup its connection.

**Comment by tsl0922** [comment] 2018-01-08 16:40
> Segmentation fault (core dumped)

If you can get the stacktrace (with gdb), it will be easier for me to identify the issue.

**Comment by realies** [comment] 2018-01-08 17:20
Perhaps rebuilding with debugging symbols would be more useful.

```
$ gdb -ex=r --args ttyd -s SIGKILL -p 8080 bash -x
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ttyd...(no debugging symbols found)...done.
Starting program: /home/realies/ttyd/build/ttyd -s SIGKILL -p 8080 bash -x
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[1515431862:8929] NOTICE: ttyd 1.3.3 (libwebsockets 1.7.1)
[1515431862:8930] NOTICE: tty configuration:
[1515431862:8936] NOTICE:   start command: bash -x
[1515431862:8936] NOTICE:   reconnect timeout: 10s
[1515431862:8936] NOTICE:   close signal: SIGKILL (9)
[1515431862:8937] NOTICE: Initial logging level 7
[1515431862:8937] NOTICE: Libwebsockets version: 1.7.1 unknown-build-hash
[1515431862:8937] NOTICE: IPV6 not compiled in
[1515431862:8937] NOTICE: libev support compiled in but disabled
[1515431862:8938] NOTICE:  Threads: 1 each 1024 fds
[1515431862:8939] NOTICE:  mem: platform fd map:  8192 bytes
[1515431862:8939] NOTICE:  mem: per-conn:          808 bytes + protocol rx buf
[1515431862:8939] NOTICE:  canonical_hostname = ubuntu
[1515431862:8940] NOTICE:  Compiled with OpenSSL support
[1515431862:8940] NOTICE:  Using non-SSL mode
[1515431862:8958] NOTICE:  SSL ECDH curve 'prime256v1'
[1515431862:8958] NOTICE:  Listening on port 8080
[1515431865:7716] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515431866:2277] NOTICE: HTTP /auth_token.js - 192.168.1.10 (192.168.1.10)
[1515431866:4603] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 1
[New Thread 0x7ffff577f700 (LWP 10344)]
[1515431866:4976] NOTICE: started process, pid: 10345
[1515431871:8957] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 2
[New Thread 0x7ffff4950700 (LWP 10355)]
[1515431871:9150] NOTICE: started process, pid: 10356
[1515431876:9586] NOTICE: sending SIGKILL (9) to process 10356
[1515431876:9591] NOTICE: process exited with code 9, pid: 10356
[1515431876:9592] NOTICE: WS closed from 192.168.1.10 (192.168.1.10), clients: 1
[Thread 0x7ffff4950700 (LWP 10355) exited]
[1515431877:0026] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515431877:4506] NOTICE: HTTP /auth_token.js - 192.168.1.10 (192.168.1.10)
[1515431877:6764] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 2
[1515431877:7215] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515431877:7220] NOTICE: WS closed from 192.168.1.10 (192.168.1.10), clients: 2
[1515431877:7220] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7223] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7225] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7227] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7228] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7331] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7434] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7541] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7644] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7746] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7849] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:7951] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:8053] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:9155] NOTICE: HTTP /auth_token.js - 192.168.1.10 (192.168.1.10)
[1515431877:9798] ERR: lws_callback_on_writable: failed to find socket -1
[1515431877:9900] ERR: lws_callback_on_writable: failed to find socket -1
[1515431878:0002] ERR: lws_callback_on_writable: failed to find socket -1
[1515431878:0105] ERR: lws_callback_on_writable: failed to find socket -1
[1515431878:0207] ERR: lws_callback_on_writable: failed to find socket -1
[1515431878:0310] ERR: lws_callback_on_writable: failed to find socket -1
[1515431878:1444] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 3
[New Thread 0x7fffefde9700 (LWP 10366)]
[1515431878:1670] NOTICE: started process, pid: 10367

Thread 1 "ttyd" received signal SIGSEGV, Segmentation fault.
0x00007ffff70fe000 in ?? () from /usr/lib/x86_64-linux-gnu/libwebsockets.so.7
```

**Comment by tsl0922** [comment] 2018-01-09 14:42
Reproduced the crash on ubuntu and debugged the code, I've identified the root cause but have no idea for it, filed an upstream issue: https://github.com/warmcat/libwebsockets/issues/1149

**Comment by tsl0922** [comment] 2018-01-09 16:14
@realies I've pushed a fix to the master branch, it works for me now (with libwebsockets 2.4.1), can you take a try? Thanks.

**Comment by realies** [comment] 2018-01-09 16:49
@tsl0922, thanks for the prompt update. It seems it does not hang this time but after the first `*** not on ah wait list ***` error occured, new clients connections will not be able to load the page, while the loaded one will continue to work.

```
[1515515614:8466] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 2
[New Thread 0x7fffefde9700 (LWP 11531)]
[1515515614:9071] NOTICE: started process, pid: 11532
[1515515623:0837] NOTICE: sending SIGKILL (9) to process 11532
[Thread 0x7fffefde9700 (LWP 11531) exited]
[1515515623:0844] NOTICE: process exited with code 9, pid: 11532
[1515515623:0845] NOTICE: WS closed from 192.168.1.10 (192.168.1.10), clients: 1
[1515515623:0973] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515624:9774] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515625:4489] NOTICE: HTTP /auth_token.js - 192.168.1.10 (192.168.1.10)
[1515515626:0268] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515631:0072] NOTICE: wsi 0x728790: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515515631:0072] ERR: *** not on ah wait list ***
[1515515651:5483] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515654:7144] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515656:6231] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515663:0077] NOTICE: wsi 0x728790: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515515663:0078] ERR: *** not on ah wait list ***
[1515515677:5488] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515684:0041] NOTICE: wsi 0x728790: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515515684:0042] ERR: *** not on ah wait list ***
[1515515707:9133] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515715:0100] NOTICE: wsi 0x728790: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515515715:0100] ERR: *** not on ah wait list ***
[1515515780:5757] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515783:8366] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515788:0083] NOTICE: wsi 0x728790: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515515788:0084] ERR: *** not on ah wait list ***
^C
Thread 1 "ttyd" received signal SIGINT, Interrupt.
0x00007ffff6c0f70d in poll () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.
```

Restarting gdb and ttyd and reloading the browser tab suddenly produces the same error:

```
[1515515979:8865] NOTICE: ttyd 1.3.3 (libwebsockets 1.7.1)
[1515515979:8865] NOTICE: tty configuration:
[1515515979:8865] NOTICE:   start command: bash -x
[1515515979:8866] NOTICE:   reconnect timeout: 10s
[1515515979:8866] NOTICE:   close signal: SIGKILL (9)
[1515515979:8866] NOTICE: Initial logging level 7
[1515515979:8866] NOTICE: Libwebsockets version: 1.7.1 unknown-build-hash
[1515515979:8866] NOTICE: IPV6 not compiled in
[1515515979:8867] NOTICE: libev support compiled in but disabled
[1515515979:8868] NOTICE:  Threads: 1 each 1024 fds
[1515515979:8868] NOTICE:  mem: platform fd map:  8192 bytes
[1515515979:8868] NOTICE:  mem: per-conn:          808 bytes + protocol rx buf
[1515515979:8869] NOTICE:  canonical_hostname = ubuntu
[1515515979:8869] NOTICE:  Compiled with OpenSSL support
[1515515979:8869] NOTICE:  Using non-SSL mode
[1515515979:8893] NOTICE:  SSL ECDH curve 'prime256v1'
[1515515979:8894] NOTICE:  Listening on port 8080
[1515515984:7525] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515515992:0046] NOTICE: wsi 0x6c7e30: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515515992:0046] ERR: *** not on ah wait list ***
```

This was also consistent to reproduce:
```
[1515516062:6451] NOTICE: ttyd 1.3.3 (libwebsockets 1.7.1)
[1515516062:6451] NOTICE: tty configuration:
[1515516062:6451] NOTICE:   start command: bash -x
[1515516062:6452] NOTICE:   reconnect timeout: 10s
[1515516062:6452] NOTICE:   close signal: SIGKILL (9)
[1515516062:6452] NOTICE: Initial logging level 7
[1515516062:6452] NOTICE: Libwebsockets version: 1.7.1 unknown-build-hash
[1515516062:6453] NOTICE: IPV6 not compiled in
[1515516062:6453] NOTICE: libev support compiled in but disabled
[1515516062:6454] NOTICE:  Threads: 1 each 1024 fds
[1515516062:6454] NOTICE:  mem: platform fd map:  8192 bytes
[1515516062:6454] NOTICE:  mem: per-conn:          808 bytes + protocol rx buf
[1515516062:6455] NOTICE:  canonical_hostname = ubuntu
[1515516062:6455] NOTICE:  Compiled with OpenSSL support
[1515516062:6456] NOTICE:  Using non-SSL mode
[1515516062:6480] NOTICE:  SSL ECDH curve 'prime256v1'
[1515516062:6480] NOTICE:  Listening on port 8080
[1515516064:1412] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515516071:0112] NOTICE: wsi 0x6c7e30: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515516071:0113] ERR: *** not on ah wait list ***
```

Had to open a private browser window in between restarts to be able to connect without any instant crashes. However, after the first connection, another error showed in the log without affecting connectivity or functionality.

```
[1515516254:8101] NOTICE:  Listening on port 8080
[1515516255:7360] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515516257:0017] NOTICE: HTTP /auth_token.js - 192.168.1.10 (192.168.1.10)
[1515516257:2009] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 1
[New Thread 0x7ffff577f700 (LWP 11632)]
[1515516257:2724] NOTICE: started process, pid: 11633
[1515516262:0060] NOTICE: wsi 0x6c7e30: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515516262:0060] ERR: *** not on ah wait list ***
[1515516283:4814] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515516285:5437] NOTICE: HTTP /auth_token.js - 192.168.1.10 (192.168.1.10)
[1515516285:7441] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 2
[New Thread 0x7ffff4950700 (LWP 11644)]
[1515516285:8065] NOTICE: started process, pid: 11645
[1515516290:0106] NOTICE: wsi 0x780510: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515516290:0107] ERR: *** not on ah wait list ***
[1515516388:7834] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[1515516391:2931] NOTICE: HTTP /auth_token.js - 192.168.1.10 (192.168.1.10)
[1515516391:4879] NOTICE: WS   /ws - 192.168.1.10 (192.168.1.10), clients: 3
[New Thread 0x7fffeffff700 (LWP 11655)]
[1515516391:5504] NOTICE: started process, pid: 11656
[1515516396:0063] NOTICE: wsi 0x7d57a0: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 0, pfd events 0)
[1515516396:0063] ERR: *** not on ah wait list ***
```

**Comment by tsl0922** [comment] 2018-01-09 16:57
The `not on ah wait list` error should be logged by libwebsockets, I didn't see this on `2.4.1` version, are you still using `1.7.1`? I'm planning to drop support for libwebsockets `1.x` 😃 .

**Comment by realies** [comment] 2018-01-09 17:23
Updating libwebsockets from `1.7.1` to `master` has produced another unexpected result.

The client does not load no matter private or normal session.

```
$ gdb -ex=r --args ttyd -s SIGKILL -p 8080 bash -x 2>&1 | tee output.log
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ttyd...(no debugging symbols found)...done.
Starting program: /home/realies/ttyd/build/ttyd -s SIGKILL -p 8080 bash -x
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2018/01/09 19:16:34:4694] NOTICE: ttyd 1.3.3 (libwebsockets 2.4.0)
[2018/01/09 19:16:34:4695] NOTICE: tty configuration:
[2018/01/09 19:16:34:4695] NOTICE:   start command: bash -x
[2018/01/09 19:16:34:4696] NOTICE:   reconnect timeout: 10s
[2018/01/09 19:16:34:4696] NOTICE:   close signal: SIGKILL (9)
[2018/01/09 19:16:34:4696] NOTICE: libuv support not compiled in
[2018/01/09 19:16:34:4696] NOTICE: Creating Vhost 'default' port 8080, 2 protocols, IPv6 off
[2018/01/09 19:17:12:9975] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[2018/01/09 19:17:12:9976] ERR:
[2018/01/09 19:17:12:9976] ERR: 0000: 3C 21 44 4F 43 54 59 50 45 20 68 74 6D 6C 3E 0A    <!DOCTYPE html>.
[2018/01/09 19:17:12:9977] ERR: 0010: 3C 68 74 6D 6C 20 6C 61 6E 67 3D 22 65 6E 22 3E    <html lang="en">
[2018/01/09 19:17:12:9977] ERR: 0020: 0A 3C 68 65 61 64 3E 0A 20 20 20 20 3C 6D 65 74    .<head>.    <met
[2018/01/09 19:17:12:9977] ERR: 0030: 61 20 63 68 61 72 73 65 74 3D 22 55 54 46 2D 38    a charset="UTF-8
[2018/01/09 19:17:12:9977] ERR: 0040: 22 3E 0A 20 20 20 20 3C 6D 65 74 61 20 68 74 74    ">.    <meta htt
[2018/01/09 19:17:12:9977] ERR: 0050: 70 2D 65 71 75 69 76 3D 22 58 2D 55 41 2D 43 6F    p-equiv="X-UA-Co
[2018/01/09 19:17:12:9978] ERR: 0060: 6D 70 61 74 69 62 6C 65 22 20 63 6F 6E 74 65 6E    mpatible" conten
[2018/01/09 19:17:12:9978] ERR: 0070: 74 3D 22 49 45 3D 65 64 67 65 2C 63 68 72 6F 6D    t="IE=edge,chrom
[2018/01/09 19:17:12:9978] ERR: 0080: 65 3D 31 22 3E 0A 20 20 20 20 3C 74 69 74 6C 65    e=1">.    <title
[2018/01/09 19:17:12:9978] ERR: 0090: 3E 74 74 79 64 20 2D 20 54 65 72 6D 69 6E 61 6C    >ttyd - Terminal
[2018/01/09 19:17:12:9978] ERR: 00A0: 3C 2F 74 69 74 6C 65 3E 0A 20 20 20 20 3C 6C 69    </title>.    <li
[2018/01/09 19:17:12:9978] ERR: 00B0: 6E 6B 20 72 65 6C 3D 22 69 63 6F 6E 22 20 74 79    nk rel="icon" ty
[2018/01/09 19:17:12:9979] ERR: 00C0: 70 65 3D 22 69 6D 61 67 65 2F 70 6E 67 22 20 68    pe="image/png" h
[2018/01/09 19:17:12:9979] ERR: 00D0: 72 65 66 3D 22 64 61 74 61 3A 69 6D 61 67 65 2F    ref="data:image/
[2018/01/09 19:17:12:9979] ERR: 00E0: 70 6E 67 3B 62 61 73 65 36 34 2C 69 56 42 4F 52    png;base64,iVBOR
[2018/01/09 19:17:12:9979] ERR: 00F0: 77 30 4B 47 67 6F 41 41 41 41 4E 53 55 68 45 55    w0KGgoAAAANSUhEU
[2018/01/09 19:17:12:9979] ERR: 0100: 67 41 41 41 43 41 41 41 41 41 63 43 41 59 41 41    gAAACAAAAAcCAYAA
...
[2018/01/09 19:18:37:7941] ERR: 
[2018/01/09 19:18:37:7941] ERR: ** 0x6aaaf0: vh: default, prot: http-only, Illegal back-to-back write of 492019 detected...
```

**Comment by tsl0922** [comment] 2018-01-10 01:16
Yes, it is broken with libwebsockets master/v2.5 (not released), please use the latest stable release instead.

https://github.com/warmcat/libwebsockets/blob/master/READMEs/README.coding.md
> From v2.5, lws strictly enforces only one lws_write() per WRITEABLE callback.
>
> You will receive a message about "Illegal back-to-back write of ... detected" if there is a second lws_write() before returning to the event loop.

**Comment by realies** [comment] 2018-01-12 20:17
Getting the same result when recompiling with libwebsockets v2.4-stable.

```
$ gdb -ex=r --args ttyd -s SIGKILL -p 8080 bash -x
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ttyd...(no debugging symbols found)...done.
Starting program: /home/realies/ttyd/build/ttyd -s SIGKILL -p 8080 bash -x
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2018/01/12 21:57:59:6372] NOTICE: ttyd 1.3.3 (libwebsockets 2.4.0)
[2018/01/12 21:57:59:6372] NOTICE: tty configuration:
[2018/01/12 21:57:59:6372] NOTICE:   start command: bash -x
[2018/01/12 21:57:59:6373] NOTICE:   reconnect timeout: 10s
[2018/01/12 21:57:59:6373] NOTICE:   close signal: SIGKILL (9)
[2018/01/12 21:57:59:6373] NOTICE: libuv support not compiled in
[2018/01/12 21:57:59:6374] NOTICE: Creating Vhost 'default' port 8080, 2 protocols, IPv6 off
[2018/01/12 21:58:09:0751] NOTICE: HTTP / - 192.168.1.10 (192.168.1.10)
[2018/01/12 21:58:09:0752] ERR: 
[2018/01/12 21:58:09:0753] ERR: 0000: 3C 21 44 4F 43 54 59 50 45 20 68 74 6D 6C 3E 0A    <!DOCTYPE html>.
[2018/01/12 21:58:09:0753] ERR: 0010: 3C 68 74 6D 6C 20 6C 61 6E 67 3D 22 65 6E 22 3E    <html lang="en">
[2018/01/12 21:58:09:0753] ERR: 0020: 0A 3C 68 65 61 64 3E 0A 20 20 20 20 3C 6D 65 74    .<head>.    <met
[2018/01/12 21:58:09:0754] ERR: 0030: 61 20 63 68 61 72 73 65 74 3D 22 55 54 46 2D 38    a charset="UTF-8
[2018/01/12 21:58:09:0754] ERR: 0040: 22 3E 0A 20 20 20 20 3C 6D 65 74 61 20 68 74 74    ">.    <meta htt
[2018/01/12 21:58:09:0755] ERR: 0050: 70 2D 65 71 75 69 76 3D 22 58 2D 55 41 2D 43 6F    p-equiv="X-UA-Co
[2018/01/12 21:58:09:0755] ERR: 0060: 6D 70 61 74 69 62 6C 65 22 20 63 6F 6E 74 65 6E    mpatible" conten
[2018/01/12 21:58:09:0755] ERR: 0070: 74 3D 22 49 45 3D 65 64 67 65 2C 63 68 72 6F 6D    t="IE=edge,chrom
[2018/01/12 21:58:09:0755] ERR: 0080: 65 3D 31 22 3E 0A 20 20 20 20 3C 74 69 74 6C 65    e=1">.    <title
[2018/01/12 21:58:09:0756] ERR: 0090: 3E 74 74 79 64 20 2D 20 54 65 72 6D 69 6E 61 6C    >ttyd - Terminal
[2018/01/12 21:58:09:0756] ERR: 00A0: 3C 2F 74 69 74 6C 65 3E 0A 20 20 20 20 3C 6C 69    </title>.    <li
[2018/01/12 21:58:09:0757] ERR: 00B0: 6E 6B 20 72 65 6C 3D 22 69 63 6F 6E 22 20 74 79    nk rel="icon" ty
[2018/01/12 21:58:09:0757] ERR: 00C0: 70 65 3D 22 69 6D 61 67 65 2F 70 6E 67 22 20 68    pe="image/png" h
[2018/01/12 21:58:09:0757] ERR: 00D0: 72 65 66 3D 22 64 61 74 61 3A 69 6D 61 67 65 2F    ref="data:image/
[2018/01/12 21:58:09:0757] ERR: 00E0: 70 6E 67 3B 62 61 73 65 36 34 2C 69 56 42 4F 52    png;base64,iVBOR
[2018/01/12 21:58:09:0758] ERR: 00F0: 77 30 4B 47 67 6F 41 41 41 41 4E 53 55 68 45 55    w0KGgoAAAANSUhEU
```

**Comment by tsl0922** [comment] 2018-01-13 09:58
@realies sorry, stable means tagged release, aka the [Release](https://github.com/warmcat/libwebsockets/releases) page, I've created an issue to track this (#86).

**Closed** 2018-01-13 10:01 UTC
Labels: bug
