### ISSUE TITLE
Is there any way to get user's input content?

### ISSUE THREAD

**Issue by xtuer** [tsl0922/ttyd#1168] opened 2023-07-05 00:17 UTC
Want to get the user's input content and send it to 3td server so that later to audit:

1. User input something and press enter.
2. Monitoring the user's input content.
3. Programming to send user's input content to 3td server.

**Comment by tsl0922** [comment] 2023-07-05 07:34
duplicate of #251

**Closed by tsl0922** 2023-07-05 07:34 UTC
Labels: enhancement
