### ISSUE TITLE
Pre-compilled binaries fail to create UNIX domain sockets

### ISSUE THREAD

**Issue by oskar456** [tsl0922/ttyd#414] opened 2020-07-21 14:06 UTC
**Describe the bug**
When trying to use the pre-built binary of `ttyd` 1.6.1 with `-i socket.sock` it will not create the socket itself. The bug does not occur when `ttyd` is build locally on an x86_64 Ubuntu so the bug is probably related to different `libc` implementation used for the pre-build binaries.

**To Reproduce**
1. Download a released binary: `$ wget https://github.com/tsl0922/ttyd/releases/download/1.6.1/ttyd_linux.x86_64`
2. Make it execurtable: `$ chmod +x ttyd_linux.x86_64`
3. Run it like this: `$ ./ttyd_linux.x86_64 -i socket.sock bash`
4. See error:

```
[2020/07/21 13:56:07:5179] N: ttyd 1.6.1-079aa68 (libwebsockets 4.0.19)
[2020/07/21 13:56:07:5183] N: tty configuration:
[2020/07/21 13:56:07:5186] N:   start command: bash
[2020/07/21 13:56:07:5189] N:   close signal: SIGHUP (1)
[2020/07/21 13:56:07:5192] N:   terminal type: xterm-256color
[2020/07/21 13:56:07:5196] N:  Using foreign event loop...
[2020/07/21 13:56:07:5203] E: VH default: iface socket.sock port 7681 DOESN'T EXIST
[2020/07/21 13:56:07:5207] N:  Listening on port: 7681
```

The app is actually not listening on the stated port nor any socket exists.

**Expected behavior**
A `socket.sock` should be created in current directory.

**Environment:**
 - OS: Ubuntu 18.04.3 LTS x86_64

**Additional context**
It works properly when building `ttyd` [from source](https://github.com/tsl0922/ttyd#install-on-linux) so this bug is probably caused by musl libc used for pre-built binaries.

**Comment by tsl0922** [comment] 2020-07-25 01:00
Does the libwebsockets version used on compiling was the same with the static version (4.0.19)?

The [1.6.0](https://github.com/tsl0922/ttyd/releases/download/1.6.0/ttyd_linux.x86_64) version works (with libwebsockets 3.2.0), I didn't change the musl libc used for cross compile, so maybe the libwebsockets's unix socket feature is broken on 4.0.19.

**Comment by tsl0922** [comment] 2020-07-26 02:58
Should be fixed on master now, it's caused by an upstream behavior change.

**Closed by tsl0922** 2020-07-26 02:58 UTC
Labels: bug

**Comment by oskar456** [comment] 2020-07-26 07:39
Awesome, thank you! In the meantime, the problem can be also worked around by using `-p 0` command line option.
