### ISSUE TITLE
enhancement - bind to IP and display full URL in 

### ISSUE THREAD

**Issue by dch** [tsl0922/ttyd#71] opened 2017-09-29 10:59 UTC
Just tried ttyd today and found it wasn't easy to work out *which* IP address it's accessible on as the computer has multiple IPv4 and IPv6 addresses and interfaces.

- it would be nice to display a full URL although I can understand this might prove difficult to work out what the "best" address would be
- i would be nice to specify an IP address for ttyd to bind to,and not just an interface

Use case is that we have computers with multiple IP addresses on different networks, some secure (vpn) & some public, and knowing which IP ttyd will bind to is important for staying secure on the safe network.

**Comment by tsl0922** [comment] 2017-09-29 12:27
This should already works (at least on *nix) with the `-i` option, try `ttyd -i 127.0.0.1`.

Feel free to reopen if you have problems with this.

**Comment by dch** [comment] 2017-09-29 21:56
@tsl0922 thanks - the docs state `    --interface, -i         Network interface to bind (eg: eth0), or UNIX domain socket path (eg: /var/run/ttyd.sock)` can you amend that to "IP address or Network interface to bind (eg: eth0), or UNIX domain socket path (eg: /var/run/ttyd.sock)` for the next person?

Also, when I run this on FreeBSD I get:

```
 ttyd -i 172.16.1.14 tmux -u new
[2017/09/29 21:52:28:0244] NOTICE: ttyd 1.3.3 (libwebsockets 2.2.2)
[2017/09/29 21:52:28:0244] NOTICE: tty configuration:
[2017/09/29 21:52:28:0244] NOTICE:   start command: tmux -u new
[2017/09/29 21:52:28:0244] NOTICE:   reconnect timeout: 10s
[2017/09/29 21:52:28:0244] NOTICE:   close signal: SIGHUP (1)
[2017/09/29 21:52:28:0244] NOTICE: Initial logging level 7
[2017/09/29 21:52:28:0244] NOTICE: Libwebsockets version: 2.2.2 unknown-build-hash
[2017/09/29 21:52:28:0244] NOTICE: IPV6 compiled in and enabled
[2017/09/29 21:52:28:0244] NOTICE: libev support not compiled in
[2017/09/29 21:52:28:0244] NOTICE: libuv support not compiled in
[2017/09/29 21:52:28:0245] NOTICE:  Threads: 1 each 3770172 fds
[2017/09/29 21:52:28:0543] NOTICE:  mem: platform fd map: 30161376 bytes
[2017/09/29 21:52:28:0543] NOTICE:  Compiled with OpenSSL support
[2017/09/29 21:52:28:0543] NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2017/09/29 21:52:28:0543] NOTICE: Creating Vhost 'default' port 7681, 2 protocols, IPv6 on
[2017/09/29 21:52:28:0553] ERR: ERROR on binding fd 6 to port 7681 (-1 48)
[2017/09/29 21:52:28:0553] ERR: init server failed
[2017/09/29 21:52:28:0553] ERR: Failed to create default vhost
[2017/09/29 21:52:28:0553] ERR: libwebsockets init failed
```

however trying it on a different IP does work:

```
 ttyd -i  fe80::ae1f:6bff:fe15:2d78  tmux -u new
[2017/09/29 21:54:23:1437] NOTICE: ttyd 1.3.3 (libwebsockets 2.2.2)
[2017/09/29 21:54:23:1437] NOTICE: tty configuration:
[2017/09/29 21:54:23:1437] NOTICE:   start command: tmux -u new
[2017/09/29 21:54:23:1437] NOTICE:   reconnect timeout: 10s
[2017/09/29 21:54:23:1437] NOTICE:   close signal: SIGHUP (1)
[2017/09/29 21:54:23:1437] NOTICE: Initial logging level 7
[2017/09/29 21:54:23:1437] NOTICE: Libwebsockets version: 2.2.2 unknown-build-hash
[2017/09/29 21:54:23:1437] NOTICE: IPV6 compiled in and enabled
[2017/09/29 21:54:23:1437] NOTICE: libev support not compiled in
[2017/09/29 21:54:23:1437] NOTICE: libuv support not compiled in
[2017/09/29 21:54:23:1438] NOTICE:  Threads: 1 each 3770172 fds
[2017/09/29 21:54:23:1763] NOTICE:  mem: platform fd map: 30161376 bytes
[2017/09/29 21:54:23:1763] NOTICE:  Compiled with OpenSSL support
[2017/09/29 21:54:23:1764] NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2017/09/29 21:54:23:1764] NOTICE: Creating Vhost 'default' port 7681, 2 protocols, IPv6 on
[2017/09/29 21:54:23:1773] NOTICE:  Listening on port 7681
[2017/09/29 21:54:23:1773] NOTICE:  mem: per-conn:          568 bytes + protocol rx buf
[2017/09/29 21:54:23:1773] NOTICE:  canonical_hostname = wintermute.skunkwerks.at
^C[2017/09/29 21:54:30:2058] NOTICE: received signal: SIGINT (2), exiting...
[2017/09/29 21:54:30:2058] NOTICE: send ^C to force exit.
[2017/09/29 21:54:30:2059] NOTICE: lws_context_destroy: ctx 0x8006ab000
[2017/09/29 21:54:30:2059] NOTICE: lws_context_destroy2: ctx 0x8006ab000
```

I'm not clear what the difference between these interfaces is;

```
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e505bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,LRO,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether ac:1f:6b:15:2d:78
	inet6 fe80::ae1f:6bff:fe15:2d78%igb0 prefixlen 64 scopeid 0x1 
	inet 172.16.1.14 netmask 0xffffff00 broadcast 172.16.1.255 
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e505bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,LRO,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether ac:1f:6b:15:2d:79
	inet 192.168.0.0 netmask 0xffff0000 broadcast 192.168.255.255 
	inet6 fe80::ae1f:6bff:fe15:2d79%igb1 prefixlen 64 scopeid 0x2 
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet 10.241.0.0 netmask 0xffff0000 
	inet 10.241.0.1 netmask 0xffffffff 
	inet 10.241.0.2 netmask 0xffffffff 
	inet 10.241.0.3 netmask 0xffffffff 
	inet 10.241.0.4 netmask 0xffffffff 
	inet 10.241.0.5 netmask 0xffffffff 
	inet 10.241.0.6 netmask 0xffffffff 
	inet 10.241.0.7 netmask 0xffffffff 
	inet 10.241.0.8 netmask 0xffffffff 
	inet 10.241.0.9 netmask 0xffffffff 
	inet 10.241.0.10 netmask 0xffffffff 
	inet 10.241.0.12 netmask 0xffffffff 
	inet 10.241.0.13 netmask 0xffffffff 
	inet 10.241.0.14 netmask 0xffffffff 
	inet 10.241.0.15 netmask 0xffffffff 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	groups: lo 
zt1flo98dm0peka: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 5000 mtu 2800
	options=80000<LINKSTATE>
	ether 8a:58:82:3c:2f:91
	hwaddr 00:bd:8d:32:f7:09
	inet 10.244.23.143 netmask 0xffff0000 broadcast 10.244.255.255 
	inet6 fc7b:dbb3:c9e2:8e50:6c98::1 prefixlen 40 
	inet6 fc7b:dbb3:c9e2:8e50:6c98::2 prefixlen 128 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	groups: tap 
	Opened by PID 1322
zt1flo98dm17np8: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 5000 mtu 2800
	options=80000<LINKSTATE>
	ether 2a:3d:9d:3c:2f:91
	hwaddr 00:bd:9d:32:f7:0a
	inet 10.144.0.2 netmask 0xffff0000 broadcast 10.144.255.255 
	inet6 fc7b:c4d6:6be2:8e50:6c98::1 prefixlen 40 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	groups: tap 
	Opened by PID 1322
```

**Comment by tsl0922** [comment] 2017-10-03 11:27
@dch sorry, I didn't test it on FreeBSD (will do it later, I'm on a vacation now).

The server functionality of ttyd is provided by the [libwebsocket](https://github.com/warmcat/libwebsockets) library, this maybe it's issue (to be confirmed).

**Comment by tsl0922** [comment] 2018-05-06 10:42
I'm closing this now since there's nothing can be done on ttyd's side, you may want to file an issue to the [libwebsockets](https://github.com/warmcat/libwebsockets) project.

**Closed by tsl0922** 2018-05-06 10:42 UTC
Labels: question
