### ISSUE TITLE
Web UI memory leak

### ISSUE THREAD

**Issue by tianyuanhao** [tsl0922/ttyd#276] opened 2020-02-21 02:05 UTC
**Describe the bug**
Web UI has a memory leak.

**To Reproduce**
1. Run `ttyd sleep 1`.
2. Open http://localhost:7681/ with a browser.

**Expected behavior**
The memory used by the browser grows evenly over time.

**Environment:**
 - OS: Ubuntu 16.04
 - Browser: Chrome 77

**Comment by tsl0922** [comment] 2020-03-07 13:07
Running `sleep 1` will produce an infinite reconnect on the browser side, it's by design.

The memory usage issue on reconnect should be resolved by 339889eadc4ab1f416d403951aea205d4c986e07.

**Closed by tsl0922** 2020-03-07 13:07 UTC
Labels: bug
