### ISSUE TITLE
Dynamic parameter from URL to execute command 

### ISSUE THREAD

**Issue by spichtjules** [tsl0922/ttyd#169] opened 2019-04-07 16:12 UTC
Hello,

I was wondering if it is possible to catch a dynamic parameter in the url in order to inject it to the specified command for ttyd ? 

Like 

http://localhost:8080/?myParam=test

And then the command would be 

echo ${myParam} 

And result in

echo test

Thanks

**Comment by tsl0922** [comment] 2019-04-11 03:56
Duplicate of #143, closing.

**Closed by tsl0922** 2019-04-11 03:56 UTC

**Comment by spichtjules** [comment] 2019-04-11 08:59
I need this particular functionnality for a team projet, is there any way we can hire you or pay you to get this functionnality ?

**Comment by tsl0922** [comment] 2019-04-11 09:46
No, I can't promise I will have time on it, this is a hobby project. 

Well, there was a PR(#34) for this feature, but I didn't merge it for security concerns at that time.

**Comment by tsl0922** [comment] 2019-04-14 14:39
@spichtjules Please take a look at the `--url-arg` option on master.

**Comment by spichtjules** [comment] 2019-04-14 15:09
@tsl0922 A big thanks ! That's exactly what i was looking for
