### ISSUE TITLE
Server might not respond after opening multiple browser windows or after hard refresh

### ISSUE THREAD

**Issue by dimara** [tsl0922/ttyd#189] opened 2019-06-12 11:46 UTC
After opening multiple browser windows or even after refreshing a **running** page the server
seems not respond to the initial request and the page hangs at "Waiting for 127.0.0.1...". 

Using netstat I observed that there are unconsumed packets in the Recv-Q of the socket:
```
tcp        0      0 127.0.0.1:39920         127.0.0.1:7681          ESTABLISHED 16169/chrome    
tcp      412      0 127.0.0.1:7681          127.0.0.1:39920         ESTABLISHED 11806/bash      
```

Using tcpdump I observed that Chrome (for some reason) **sometimes** uses an existing ESTABLISHED connection (i.e., created for a previous tab) to issue the HTTP GET /, instead of opening a new one.

After digging a bit into the code I see that ttyd only registers the `callback_http()`. In other words it is `libwebsocket` responsible for receiving data from the socket. So maybe it is not
ttyd to blame afterall...

The above is reproducible with Chrome (v66.0, v71.0) but not with Firefox.

**Comment by dimara** [comment] 2019-06-12 16:02
To reproduce it use [ttyd 1.4.4]( https://github.com/tsl0922/ttyd/releases/download/1.4.4/ttyd_linux.x86_64) and simply run:
```
ttyd -r 1 bash
```
An open a Chrome and open multiple http://127.0.0.1:7681 or try to refresh an existing one.

**Comment by aaqaishtyaq** [comment] 2019-06-13 06:51
Hey, I'm having the same issue with `ttyd` and `tmux`. After opening multiple browser windows of the same `ttyd` session.

It usually hangs up in chrome at `Waiting for cache`

**Comment by tsl0922** [comment] 2019-06-14 06:29
This is a known issue to me, should be caused by reusing connection.

**Comment by dimara** [comment] 2019-06-14 10:52
@tsl0922 Thank you for your reply. Is this a known issue with ttyd? Is it an issue with libwebsockets? Does Chrome do something wrong? Is there something ttyd can do to prevent clients from reusing a connection? Any idea/suggestion on how this could be fixed?

Btw the Linux releases have been built with libwesockets 2.4.2, right? Should we try the latest release 3.1.0 perhaps?

**Comment by tsl0922** [comment] 2019-06-14 23:45
@dimara I've figured out this, pushed a fix on master, it should works now.

**Comment by dimara** [comment] 2019-06-19 14:57
@tsl0922 I just tested the current master (after building ttyd for x86_64 with `./scripts/cross-build.sh`) and the issue still occurs. It is not obvious to me how commit  https://github.com/tsl0922/ttyd/commit/e3b569160d713c2c02076faa31de05d205d1bc50 should fix the issue, since the code path remains the same in case of libwebsockets < 3 and we use 2.4.2.
Should we re-open the issue?

**Comment by tsl0922** [comment] 2019-06-19 15:19
@dimara  I fixed it on master for libwebsockets 3.1.0, reopening.

**Comment by dimara** [comment] 2019-06-20 12:18
I confirm that building master (commit https://github.com/tsl0922/ttyd/commit/11c1e1bc79f8405f9) with libwebsockets 3.1.0 seems to resolve the issue (at least I cannot reproduce it).

So commit https://github.com/tsl0922/ttyd/commit/e3b569160d713c2c02076faa31de05d205d1bc50 fixed a **ttyd bug** on how it was using libwebsockets 3.1.0. Is it possible to fix ttyd to work with earlier versions too? Or libwebsockets has a bug on its own?

BTW, the pre-compiled public releases of ttyd use libwebsockets 2.4.2, right? Are they artifacts of `scritps/cross-build.sh`? Will the next release use the latest libwebsockets?

**Comment by tsl0922** [comment] 2019-06-20 13:39
Yes, will bump to libwebsockets 3.x.

I have no idea for this issue on libwebsockets 2.4.2 for now.

**Comment by vkoukis** [comment] 2019-06-20 14:33
@tsl0922 I'm a colleague of @dimara 's, thank you for ttyd, we are happy users of it.
I understand this bug is now fixed for libwebsockets 3.x, but it's not obvious to me exactly what the problem was in the first place.

Can you provide some insight on exactly what was wrong and what your commit did to fix it? We  would love to understand more about its architecture and code. Thanks!

**Comment by tsl0922** [comment] 2019-06-22 10:08
libwebsockets 2.4.2 should work now on master.

**Closed by tsl0922** 2019-06-22 10:08 UTC
Labels: bug

**Comment by vkoukis** [comment] 2019-06-24 08:05
> libwebsockets 2.4.2 should work now on master.

@tsl0922 Thanks for fixing this for older versions as well.
I tried to look into the log for master and understand what the problem was.
Can you help my understanding by pointing to the commit(s) that fixed this issue, and maybe provide a short explanation?

I think it was one of 7901265f / c1c82b1a but I'm not sure.

**Comment by tsl0922** [comment] 2019-06-24 08:58
It's the later one, to understand it, you should read libwebsockets's doc and code.
