### ISSUE TITLE
vh: default, prot: http-only, role h1: Illegal back-to-back write of 293984 detected...

### ISSUE THREAD

**Issue by codehz** [tsl0922/ttyd#105] opened 2018-06-18 03:06 UTC
https://libwebsockets.org/lws-api-doc-v3.0-stable/html/md_READMEs_README_8coding.html#oneper

**Comment by tsl0922** [comment] 2018-06-18 03:09
Duplicate of #86

**Closed by tsl0922** 2018-06-18 03:09 UTC
