### ISSUE TITLE
Stopping the Docker container after client disconnects

### ISSUE THREAD

**Issue by supriyo-biswas** [tsl0922/ttyd#128] opened 2018-09-25 04:14 UTC
In the README, there is an example of allocating new Docker containers per client connection:

```
ttyd docker run -it --rm ubuntu /bin/bash
```

This works, but if I close the browser without typing `exit`, the container is left running in the background, and I have to stop it manually.

How can I prevent the container from running in the background?

**Comment by tsl0922** [comment] 2018-09-25 07:10
Duplicate of #89.

**Closed by tsl0922** 2018-09-25 07:10 UTC
