### ISSUE TITLE
Wont respond to new connections after running for a few days

### ISSUE THREAD

**Issue by dimraft** [tsl0922/ttyd#135] opened 2018-11-05 20:38 UTC
I have observed an issue a few times now where ttyd accepts connections but won't respond with any content. This seems to occur when it's been running for a number of days, but it's not clear exactly what conditions on the machine trigger this to happen. Once it's in this state, the only way to resolve the issue is to restart ttyd.

I use ttyd with the following command line options:
ttyd -p 2345 -O -d 0 login

The OS is Debian 9.

**Comment by tsl0922** [comment] 2018-12-08 05:01
Please attach the result of `netstat -an | grep 2345` when you see it happens again. If possible, you may use `strace` to check where the program stucks on.

**Comment by dimraft** [comment] 2018-12-08 06:45
I run ttyd like this:
ttyd -p 8348 -O -d 0 login
(I use -O so that only connections from localhost are accepted, and I use ssh tunnels to access it. This works really well. ttyd behaves exactly as expected 99% of the time.)

Doing a test with:
curl localhost:8348
usually returns the html for ttyd.

However, when it get's stuck, curl just hangs and doesn't return anything.

Doing netstat:
pi@raspberrypi:~ $ netstat -an | grep 8348
tcp        3      0 0.0.0.0:8348            0.0.0.0:*               LISTEN     
tcp      873      0 127.0.0.1:8348          127.0.0.1:48768         CLOSE_WAIT 
tcp      845      0 127.0.0.1:8348          127.0.0.1:48772         CLOSE_WAIT 
tcp      873      0 127.0.0.1:8348          127.0.0.1:48872         CLOSE_WAIT

**Comment by dimraft** [comment] 2018-12-08 07:00
All the CLOSE_WAIT sockets makes me thing that if the network connection is interrupted somehow and not closed cleanly, ttyd doesn't completely shutdown its side the socket.
Do you think this is the issue?

**Comment by tsl0922** [comment] 2019-04-17 10:54
This may be fixed on master, I can't reproduce it  now.

Closing, feel free to reopen if you can reproduce it on master.

**Closed by tsl0922** 2019-04-17 10:54 UTC
Labels: bug
